host = "0.0.0.0"
port = 25565
motd = ["Welcome to the best server ever!", "Rust", "Good luck, have fun!"]
max_players = 100
tps = 20
world = "ferrite"
whitelist = false
network_compression_threshold = 64

verify_decompressed_packets = true
encryption_enabled = false
online_mode = false
chunk_render_distance = 12

default_gamemode = "creative"

[database]
db_path = "world"
verify_chunk_data = true
map_size = 1_000
cache_ttl = 60
cache_capacity = 20_000

[performance]
chunks_per_tick = 0
chunks_per_tick_min = 16

[dashboard]
port = 9000
secret = "EYWluvjBqLpzkwXoTNTGKuvrl7RMFyTc"
